version: "3.8"

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/WebAPI/Dockerfile
    ports:
      - "5000:8080"  #maps host 5000 → container 8080
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=UserManagement;User=sa;Password=P@ssword@123;
    depends_on:
      - sqlserver
  

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword@123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - webapi
  
  adminer:
   image: adminer
   container_name: adminer
   ports:
    - "8082:8080"
   depends_on:
    - sqlserver
 
volumes:
  sqlserverdata: