version: "3.8"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword@123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  adminer:
   image: adminer
   container_name: adminer
   ports:
    - "8082:8080"
   depends_on:
    - sqlserver

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/WebAPI/Dockerfile
    ports:
      - "5000:8080" 
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=UserManagement;User=sa;Password=P@ssword@123;TrustServerCertificate=True;    
    depends_on:
      - sqlserver

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    container_name: webapp
    build:
      context: .
      dockerfile: src/BlazorClient/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - webapi
 
volumes:
  sqlserverdata:
