name: Deploy WebAPI and Blazor WASM to Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
   AZURE_WEBPP_NAME: time-service
   DOTNET_VERSION: '9.x'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore src/WebAPI/WebAPI.csproj

      - name: Build solution
        run: dotnet build src/WebAPI/WebAPI.csproj --configuration Release --no-restore

      - name: Publish WebAPI
        run: dotnet publish src/WebAPI/WebAPI.csproj -c Release -o WebAPIApp

      - name: Upload WebAPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapi-artifact
          path: ./artifacts/webapi

deploy:
  name: Deploy to Azure
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Download WebAPI artifact
      uses: actions/download-artifact@v4
    with:
      name: webapi-artifact
      path: ./webapi


    -name: Deploy WebAPI to Azure 
     uses: azure/webapps-deploy@v2
     with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./webapi

