name: Build and Deploy .NET WebAPI and Blazor WASM

on:
  push:
    branches: [main]

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    name: Build Projects and Publish Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Publish WebAPI
        run: dotnet publish ./src/WebAPI/WebAPI.csproj -c Release -o ./publish/WebAPI

      - name: Publish Blazor WASM
        run: dotnet publish ./src/BlazorClient/BlazorClient.csproj -c Release -o ./publish/BlazorClient

      - name: Upload WebAPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapi-publish
          path: ./publish/WebAPI

      - name: Upload BlazorClient artifact
        uses: actions/upload-artifact@v4
        with:
          name: blazor-publish
          path: ./publish/BlazorClient/wwwroot
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download WebAPI artifact
        uses: actions/download-artifact@v4
        with:
          name: webapi-publish
          path: ./deploy/webapi

      - name: Download BlazorClient artifact
        uses: actions/download-artifact@v4
        with:
          name: blazor-publish
          path: ./deploy/blazor

      - name: Deploy WebAPI to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./deploy/webapi

      - name: Deploy Blazor WASM to Azure Static Web App
        uses: azure/static-web-apps-deploy@v1
        with:
          app_location: './deploy/blazor'
          output_location: ''
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
